<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<OutDir>bin</OutDir>
	<AssemblyName>NMFSolution</AssemblyName>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Families.nmeta" />
    <None Remove="Persons.nmeta" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Families.nmeta" />
    <EmbeddedResource Include="Persons.nmeta" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NMF-Repository" Version="3.0.0" />
    <PackageReference Include="NMF-Synchronizations" Version="3.0.1" />
  </ItemGroup>

</Project>
