package org.benchmarx.examples.familiestopersons.implementations.eneo;

public enum EDIT_TYPE {
	CREATE_FAMILY, CREATE_FAMILY_MEMBER, CREATE_FAMILY_REGISTER__FAMILIES, CREATE_FAMILY__SONS,
	CREATE_FAMILY__DAUGHTERS, CREATE_FAMILY__MOTHER, CREATE_FAMILY__FATHER, CHANGE_FAMILY__NAME, DELETE_FAMILY,
	DELETE_FAMILY_MEMBER, MOVE_FAMILY_MEMBER, DELETE_FAMILY_REGISTER__FAMILIES, DELETE_FAMILY__FATHER,
	DELETE_FAMILY__MOTHER, DELETE_FAMILY__SONS, DELETE_FAMILY__DAUGHTERS, CREATE_MALE, CREATE_FEMALE, DELETE_PERSON,
	CREATE_PERSON_REGISTER__PERSONS, DELETE_PERSON_REGISTER__PERSONS, CHANGE_BIRTHDAY, CHANGE_PERSON__NAME
}
