<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="CompositeList" nsURI="CompositeList" nsPrefix="CompositeList">
  <eClassifiers xsi:type="ecore:EClass" name="List">
    <eOperations name="add" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="newElement" eType="#//DataElement"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//Node"
        eOpposite="#//Node/startOf"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//Node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node" abstract="true">
    <eOperations name="addLast" eType="#//Node">
      <eParameters name="newNode" eType="#//DataNode"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="startOf" eType="#//List"
        eOpposite="#//List/start"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataNode" eSuperTypes="#//Node">
    <eOperations name="addLast" eType="#//Node">
      <eParameters name="newNode" eType="#//DataNode"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="follower" eType="#//Node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Leaf" eSuperTypes="#//Node">
    <eOperations name="addLast" eType="#//Node">
      <eParameters name="newNode" eType="#//DataNode"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataElement" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Pair">
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        eType="#//Value" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" eType="#//Key" containment="true"
        eOpposite="#//Key/pair"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Key">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keyValues" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pair" eType="#//Pair" eOpposite="#//Pair/key"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Value" eSuperTypes="#//DataElement"/>
</ecore:EPackage>
