<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="IBeXTGGGantt2CPM" nsURI="platform:/resource/IBeXTGGGantt2CPM/model/IBeXTGGGantt2CPM.ecore"
    nsPrefix="IBeXTGGGantt2CPM">
  <eClassifiers xsi:type="ecore:EClass" name="DiagramToNetwork">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/Gantt/model/Gantt.ecore#//GanttDiagram"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/CPM/model/CPM.ecore#//CPMNetwork"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityToActivity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/Gantt/model/Gantt.ecore#//Activity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/CPM/model/CPM.ecore#//Activity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DependencyToActivity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/Gantt/model/Gantt.ecore#//Dependency"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/CPM/model/CPM.ecore#//Activity"/>
  </eClassifiers>
</ecore:EPackage>
