<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="IBeXTGGPetrinets" nsURI="platform:/resource/IBeXTGGPetrinets/model/IBeXTGGPetrinets.ecore"
    nsPrefix="IBeXTGGPetrinets">
  <eClassifiers xsi:type="ecore:EClass" name="NetToNet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/Petrinet/model/PetriNet.ecore#//Net"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/PetrinetWeighted/model/PetriNetWeighted.ecore#//Net"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransToTrans">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/Petrinet/model/PetriNet.ecore#//Transition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/PetrinetWeighted/model/PetriNetWeighted.ecore#//Transition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlaceToPlace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/Petrinet/model/PetriNet.ecore#//Place"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/PetrinetWeighted/model/PetriNetWeighted.ecore#//Place"/>
  </eClassifiers>
</ecore:EPackage>
