<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="osets" nsURI="http://de.ubt.ai1.bw.qvt.examples.osets.ecore"
    nsPrefix="osets">
  <eClassifiers xsi:type="ecore:EClass" name="MyOrderedSet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" ordered="false"
        upperBound="-1" eType="#//Element" containment="true" eOpposite="#//Element/orderedSet"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="incrementalID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="next" eType="#//Element"
        eOpposite="#//Element/previous"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="previous" eType="#//Element"
        eOpposite="#//Element/next"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orderedSet" eType="#//MyOrderedSet"
        eOpposite="#//MyOrderedSet/elements"/>
  </eClassifiers>
</ecore:EPackage>
