<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="IBeXTGGEcoreToSQL" nsURI="platform:/resource/IBeXTGGEcoreToSQL/model/IBeXTGGEcoreToSQL.ecore"
    nsPrefix="IBeXTGGEcoreToSQL">
  <eClassifiers xsi:type="ecore:EClass" name="PackageToSchema">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/SQL/model/SQL.ecore#//Schema"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassToTable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/SQL/model/SQL.ecore#//Table"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PackageToTable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/SQL/model/SQL.ecore#//Table"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttrToCol">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/SQL/model/SQL.ecore#//Column"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RefToFKey">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/SQL/model/SQL.ecore#//ForeignKey"/>
  </eClassifiers>
</ecore:EPackage>
